### ISSUE TITLE
Package renaming

### ISSUE THREAD

**Issue by rfairley** [rfairley/fedora-coreos-metrics-client#16]
`metrics` can be confused with other projects that deal with metrics. For now, the package just needs a quick name to be included in an initial FCOS release, which is descriptive enough and doesn't conflict with other projects.

For now, a descriptive name which doesn't conflate the `metrics` topic would be enough.

**Comment by rfairley** [comment]
Some suggestions from chat with @jlebon, @lucab, @bgilbert :

```
fedora-coreos-usage-ping
fedora-coreos-telemeter
fedora-coreos-usage-client
fedora-coreos-usage-stats
fedora-coreos-pinger
```

Edit: as @lucab noted in chat, GitLab has a feature called `usage-ping` https://docs.gitlab.com/ee/user/admin_area/settings/usage_statistics.html#usage-ping-core-only which is also an opt-out feature (which may be recognizable as to what this package does).

**Comment by rfairley** [comment]
```
fedora-coreos-usage-ping
fedora-coreos-usage-client
fedora-coreos-pinger
```

I'd be good with any of these (as a conflict with https://github.com/openshift/telemeter was noted in chat).

**Comment by rfairley** [comment]
Overall preference in chat was for

```
fedora-coreos-usage-client
fedora-coreos-pinger
```

**Comment by bgilbert** [comment]
Of those, I'd prefer `fedora-coreos-pinger`.

**Comment by jlebon** [comment]
> ```
> fedora-coreos-usage-client
> fedora-coreos-pinger
> ```

Good with either of those on my side. Seems like `pinger` is already [something](https://en.wikipedia.org/wiki/Pinger), though whatever we choose I don't think getting good SEO for `fedora coreos pinger` would be very hard. I like that the `ping` bit makes it more obvious that we transmit data over the network.

**Comment by rfairley** [comment]
`fedora-coreos-pinger` looks to be the preference - will plan to go ahead with the renaming to this by end of the week (on Friday).

**Comment by rfairley** [comment]
New crate is uploaded: https://crates.io/crates/fedora-coreos-pinger
