### ISSUE TITLE
crates.io: add team ownership

### ISSUE THREAD

**Issue by lucab** [rfairley/fedora-coreos-metrics-client#25]
According to https://crates.io/crates/fedora-coreos-pinger, @rfairley is the only one who can publish the `fedora-coreos-pinger` crate. We should mitigate the bus-factor by adding team ownership.

@rfairley can you please run a `cargo owner --add github:coreos:team-os-internal-crates-owners  -- fedora-coreos-pinger`. If that does not work due to permission issues, feel free to just add myself (`lucab`) and I can push that forward to the team.

**Comment by rfairley** [comment]
Thanks! Just sent an owner invite to your account `lucab` (hit a permission issue with the above `cargo owner` command). Feel free to run that command at your convenience.

**Comment by lucab** [comment]
Thanks, invite accepted and team-ownership added. Closing this.
